on: [ push ]
jobs:
  check_dry_run_no_branches:
    runs-on: ubuntu-latest
    name: Runs the action with no ignore branches
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run our action
        uses: ./
        id: delete_stuff
        with:
          github_token: ${{ github.token }}
          last_commit_age_days: 9
          dry_run: no

      - name: Get output
        run: "echo 'Deleted branches: ${{ steps.delete_stuff.outputs.deleted_branches }}'"
