name: Quick tests against our own repository

on:
  push:

  # Allow workflow to be manually run from the GitHub UI
  workflow_dispatch:
jobs:
  check_dry_run_no_branches:
    runs-on: ubuntu-latest
    name: Runs the action with no ignore branches
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build action container
        run: docker build -t action_container .

      - name: "Test: default options"
        run: |
          docker run --rm -t \
            -e GITHUB_REPOSITORY \
            -e GITHUB_OUTPUT \
            -v "${GITHUB_OUTPUT}:${GITHUB_OUTPUT}" \
            action_container \
            --github-token="${{ github.token }}"

      - name: "Test: ignore branch 'test_prefix/two'"
        run: |
          docker run --rm -t \
            -e GITHUB_REPOSITORY \
            -e GITHUB_OUTPUT \
            -v "${GITHUB_OUTPUT}:${GITHUB_OUTPUT}" \
            action_container \
            --ignore-branches="test_prefix/two" \
            --last-commit-age-days=9 \
            --dry-run=yes \
            --github-token="${{ github.token }}"

      - name: "Test: allow only`test_prefix/*` except for `test_prefix/two`"
        run: |
          docker run --rm -t \
            -e GITHUB_REPOSITORY \
            -e GITHUB_OUTPUT \
            -v "${GITHUB_OUTPUT}:${GITHUB_OUTPUT}" \
            action_container \
            --allowed-prefixes=test_prefix/ \
            --ignore-branches=test_prefix/two \
            --last-commit-age-days=9 \
            --dry-run=yes \
            --github-token="${{ github.token }}"
